spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mp?&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
logging:
  level:
    com.ls: debug
  pattern:
    dateformat: HH:mm:ss


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml  # mapper文件位置 默认值
  type-aliases-package: com.ls.mp.pojo   # 别名扫描包
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名 默认开启
    cache-enabled: false  # 二级缓存  默认不开启
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      id-type: assign_id # 全局配置主键生成策略 默认值
      update-strategy: not_null # 全局配置更新策略 只更新非空字段
      logic-delete-field: deleted # 全局逻辑删除字段



knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    email:
    concat: hnsqls
    url:
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.ls.mp.controller
